### ISSUE TITLE
oryp6/7: Changing keyboard brightness also changes color when using custom colors

### ISSUE THREAD

**Issue by MilesBHuff** [system76/ec#174]
*Cross-post from https://github.com/pop-os/system76-acpi-dkms/issues/8.*

**Distribution (run `cat /etc/os-release`):**
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
`system76-acpi-dkms 1.0.2+1+g0bc966c-1`

**Issue/Bug Description:**
Setting the keyboard of the oryp7 to anything other than `ffffff` results in completely random colors being assigned.

**Steps to reproduce (if you know):**
Set keyboard brightness to anything less than 100% (I use 20%):
```
sudo su -c 'echo 667788 > /sys/class/leds/system76_acpi::kbd_backlight/color'
# Repeat the above several times.
```

**Expected behavior:**
The setting exposed by `system76-acpi-dkms` should use the assigned hex color.

**Other Notes:**
From @jacobgkau:
> It seems like full brightness is reliable. Maybe this bug has something to do with how the black color is mixed in to lower the brightness. Certain colors (such as plain red) do work, others like `310086` purple are only broken on specific brightness levels.

From @leviport:
> I am seeing the same behavior on oryp6 when I set the backlight color to `667788` and change the brightness with the brightness hotkeys. Here is a short video of the color changing to all kinds of different colors when repeatedly moving the brightness up and down by one keypress: https://user-images.githubusercontent.com/13512097/114424105-0b6b6a80-9b75-11eb-950e-04a853f8a7df.mp4

**Comment by MilesBHuff** [comment]
Any updates on this?  Keyboard brightness is completely broken, lol.  Defeats the purpose of having brightness control buttons on the numpad.

**Comment by jacobgkau** [comment]
> Keyboard brightness is completely broken, lol.

That is an exaggeration; brightness works normally with all predefined colors. The issue is that some non-predefined colors are having the color changed along with the brightness, which is an issue that should be fixed, but is not as severe as not being able to change brightness at all.

Looking at this some more, the issue is greatly reduced when using a fully-valued color. As a workaround until this is fixed, I would recommend using a color picker like [this one](https://html-color-codes.info/old/colorpicker.html) to find the color you're wanting, making sure to leave the dot in the top right of the square (or at least along the top edge.) While I am still seeing a small variation happening with some colors (like yellow and purple shades), it seems adjusting brightness still keeps the overall color when I only use colors with a value of 100%.

Alternatively, if you have a specific brightness you're wanting to achieve, you can set the keyboard backlight to 100% and drag the dot down vertically to mix black into your color code. Reducing the value percentage in the color code will reduce brightness, even if the backlight is set to 100% power in the firmware. (This workaround is mutually exclusive to the previous one, since lowering the value is what triggers the drastic color changes on firmware brightness change.)

**Comment by MilesBHuff** [comment]
> That is an exaggeration; brightness works normally with all predefined colors. The issue is that some non-predefined colors are having the color changed along with the brightness, which is an issue that should be fixed, but is not as severe as not being able to change brightness at all.

Ah!  I see.  Thank you for that clarification.  I'm using [a program I wrote](https://github.com/MilesBHuff/Ambient-Keyboard-Lighting) that automatically sets the keyboard to the average color of the display, and since it uses non-fully-valued colors almost exclusively, the keyboard seems completely broken when I turn the brightness up and down.  If it works for all predefined colors, then yeah, this is clearly not "completely broken", and is really probably not even a priority.  I'll just make do for the time-being.  Thanks for the clarification.  :)

**Comment by MilesBHuff** [comment]
Maybe the issue has been fixed by chance since I filed the ticket;  I'll try to reproduce with the latest ec.

**Comment by crawfxrd** [comment]
It's not fixed. Setting PWM to inhibit mode while changing the values also doesn't affect the behavior.

**Comment by crawfxrd** [comment]
Might have a fix.

This should be reproducible on all board using IT5570E. What about boards using IT8587E (addw1, oryp5)?

**Comment by crawfxrd** [comment]
@jacobgkau can you check what the behavior on oryp5 or addw1 is? The IT8587E doesn't have (or at least doesn't document) the register for the fix in #304.

**Comment by jacobgkau** [comment]
I don't have either of those machines at the moment, but I'll coordinate with the team to check that.

**Comment by crawfxrd** [comment]
Actually, only addw1 uses PWM (oryp5 uses a stupid I2C config), so it won't matter since we're not making a release for addw1 in this batch.
